---
title: "Journal Article"
output: html_document
---
### A debate on regulation and energy transition in Colombia (in Spanish)
**JEL:** O32 *Management of Technological Innovation and R&D.*

**Palabras clave:** Crecimiento, Transición Energética, Medio Ambiente y Cambio Climático.

La reducción de los Gases de Efecto Invernadero, la recesión económica causada por el Covid-19 y el Cambio Climático son temas que preocupan tanto a los gobiernos nacionales como a las organizaciones internacionales (Naciones Unidas, OCDE, etc.), dado que en el último siglo la temperatura media global ha aumentado. En 2010, la temperatura media global alcanzó un máximo de 14,53ºC, como se evidencia en la Figura 1, y se registran años más calientes, afectando la producción agrícola y otras actividades económicas sujetas al clima. A partir de lo anterior, primero se discutirá la solución de estos problemas en torno a la reducción de la temperatura media global por medio de políticas eficientes que imponga el Estado colombiano a través de organismos públicos como el Ministerio de Ambiente y de Minas y Energía. En segundo lugar, se destacarán los principales avances en torno a la adopción de fuentes energéticas en Colombia, que va en línea con el Plan Nacional Energético y la intervención del Estado. Por último, se examinará el impacto de los consumidores teniendo en cuenta su huella de carbono. De esta forma, se evidenciará que el problema relacionado con la temperatura media global y las fuentes energéticas va en conjunto con el Cambio Climático. En consecuencia, se planteará a nuestros lectores una reflexión sobre el reto que presenta la obtención de nuevas fuentes energéticas.

Read the article (ed. 25) [here](http://revistasupuestos.com/ediciones).